name: Helloworldworkflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main:

jobs:
  hello:
    runs_on: ubuntu-latest
    steps:
     - uses: actions/checkout@v2
     - name: hello world
       run: echo "Hello World"
       shell: bash
